# Generated by Django 5.1.6 on 2025-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_subject_studentprofile'),
        ('teacher', '0003_attendancetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='student.subject'),
        ),
    ]
