# Generated by Django 5.1.6 on 2025-04-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_subject_studentprofile'),
        ('teacher', '0004_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='student.subject'),
        ),
    ]
