# Generated by Django 5.1.6 on 2025-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science and Engineering'), ('AI', 'Artifical Intelligence'), ('EEE', 'ELectrical Engineering')], max_length=50),
        ),
    ]
