# Generated by Django 5.1.6 on 2025-05-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_studentprofile_branch'),
        ('teacher', '0006_alter_teacherprofile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='student.subject'),
        ),
    ]
