# Generated by Django 5.1.6 on 2025-05-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_studentprofile_branch'),
        ('teacher', '0007_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetoken',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancetoken',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='student.subject'),
        ),
    ]
