# Generated by Django 5.1.6 on 2025-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_studentprofile_branch'),
        ('teacher', '0008_attendancetoken_latitude_attendancetoken_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetoken',
            name='used_by',
            field=models.ManyToManyField(blank=True, to='student.studentprofile'),
        ),
    ]
