# Generated by Django 5.1.6 on 2025-05-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_attendancetoken_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetoken',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science and Engineering'), ('AI', 'Artificial Intelligence'), ('EEE', 'Electrical Engineering')], max_length=50),
        ),
    ]
