# Generated by Django 5.1.6 on 2025-04-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='studentProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
    ]
