# Generated by Django 5.1.6 on 2025-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_subject_department_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science and Engineering'), ('AI', 'Artificial Intelligence'), ('EEE', 'Electrical Engineering')], max_length=50),
        ),
    ]
